FROM node:20-alpine

RUN apk add --no-cache netcat-openbsd

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN chmod +x wait-for.sh

EXPOSE 3333

CMD ["./wait-for.sh", "db:5432", "--", "yarn", "dev"]