FROM node:20

RUN apt-get update && apt-get install -y netcat-openbsd

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN npm install -g ts-node-dev typescript

COPY wait-for.sh ./ 
RUN chmod +x wait-for.sh

EXPOSE 3333
EXPOSE 5555

RUN npx prisma migrate deploy
CMD ["./wait-for.sh", "db:5432", "--", "ts-node-dev", "--poll", "--transpile-only", "src/server.ts"]
