name: Deploy (main)

on:
  push:
    branches: [ "main" ]

env:
  DEPLOY_PATH: ${{ secrets.SERVER_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            mkdir -p "${{ env.DEPLOY_PATH }}"
            cd "${{ env.DEPLOY_PATH }}"

            # Se não existir, clone o repo
            if [ ! -d .git ]; then
              git clone git@github.com:fiap-time-4/EducaMais-Backend.git .
            else
              git pull git@github.com:fiap-time-4/EducaMais-Backend.git main
            fi

            # Se tiver ENV_PROD_B64, grava/atualiza o .env
            if [ -n "${{ secrets.ENV_PROD_B64 }}" ]; then
              echo "${{ secrets.ENV_PROD_B64 }}" | base64 -d > .env
            fi

            docker compose down
            docker compose up -d --build
            docker image prune -f